MachinePortal/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MachinePortal.Areas.Identity.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MachinePortal/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using MachinePortal.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MachinePortal.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<MachinePortalUser> _userManager;

        public ConfirmEmailModel(UserManager<MachinePortalUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            var result = await _userManager.ConfirmEmailAsync(user, code);
            if (!result.Succeeded)
            {
                throw new InvalidOperationException($"Error confirming email for user with ID '{userId}':");
            }

            return Page();
        }
    }
}

MachinePortal/Areas/Identity/Pages/Account/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using MachinePortal.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MachinePortal.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<MachinePortalUser> _userManager;
        private readonly IEmailSender _emailSender;

        public ForgotPasswordModel(UserManager<MachinePortalUser> userManager, IEmailSender emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.Page(
                    "/Account/ResetPassword",
                    pageHandler: null,
                    values: new { code },
                    protocol: Request.Scheme);

                await _emailSender.SendEmailAsync(
                    Input.Email,
                    "Reset Password",
                    $"Please reset your password by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

MachinePortal/Areas/Identity/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MachinePortal.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ForgotPasswordConfirmation : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MachinePortal/Areas/Identity/Pages/Account/Lockout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MachinePortal.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LockoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MachinePortal/Areas/Identity/Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using MachinePortal.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MachinePortal.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<MachinePortalUser> _signInManager;
        private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(SignInManager<MachinePortalUser> signInManager, ILogger<LogoutModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToPage("/Index");
        }
    }
}

MachinePortal/Areas/Identity/Pages/Account/ResetPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MachinePortal.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class ResetPasswordConfirmationModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

MachinePortal/Areas/Identity/Pages/Account/WaitingConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MachinePortal.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class WaitingConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MachinePortal/Areas/Identity/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace MachinePortal.Areas.Identity.Pages
{
    [AllowAnonymous]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MachinePortal/Controllers/AreasController.cs
using System;

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MachinePortal.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MachinePortal.Services;
using System.Security.Claims;
using MachinePortal.Areas.Identity.Data;
using System.Web;

namespace MachinePortal.Controllers
{
    public class AreasController : BaseController<AreasController>
    {
        private readonly AreaService _AreaService;
        private readonly IHostingEnvironment _appEnvironment;

        public AreasController(IHostingEnvironment enviroment, AreaService areaService, PasswordService passwordService, PermissionsService permissionsService, IdentityContext identityContext)
        {
            _identityContext = identityContext;
            _AreaService = areaService;
            _PermissionsService = permissionsService;
            _appEnvironment = enviroment;
        }

        public async Task<IActionResult> Index()
        {
            Permissions();
            var list = await _AreaService.FindAllAsync();
            return View(list);
        }

        public IActionResult Create()
        {
            Permissions();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Area area, IFormFile image)
        {
            try
            {
                if (image != null)
                {
                    long filesSize = image.Length;
                    var filePath = Path.GetTempFileName();

                    if (image == null || image.Length == 0)
                    {
                        return Content(@"notify('', '" + "Error: File corrupted or invalid" + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
                    }

                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
                    fileName += image.FileName.Substring(image.FileName.LastIndexOf("."), (image.FileName.Length - image.FileName.LastIndexOf(".")));
                    string destinationPath = _appEnvironment.WebRootPath + "\\resources\\Areas\\Images\\" + fileName;
                    area.ImagePath = @"/resources/Areas/Images/" + fileName;

                    using (var stream = new FileStream(destinationPath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }
            }
            catch(Exception e)
            {
                return Content(@"notify('', '" + "Error on saving image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }
            
            try
            {
                await _AreaService.InsertAsync(area);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating database, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Area add successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Edit(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _AreaService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Area area, IFormFile image)
        {
            try
            {
                Area oldArea = await _AreaService.FindByIDAsync(area.ID);

                if (image != null)
                {
                    if (System.IO.File.Exists(_appEnvironment.WebRootPath + "\\" + area.ImagePath))
                    {
                        System.IO.File.Delete(_appEnvironment.WebRootPath + "\\" + area.ImagePath);
                    }

                    long filesSize = image.Length;
                    var filePath = Path.GetTempFileName();

                    if (image == null || image.Length == 0)
                    {
                        return Content(@"notify('', '" + "Error: File corrupted or invalid" + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
                    }

                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
                    fileName += image.FileName.Substring(image.FileName.LastIndexOf("."), (image.FileName.Length - image.FileName.LastIndexOf(".")));
                    string destinationPath = _appEnvironment.WebRootPath + "\\resources\\Areas\\Images\\" + fileName;
                    area.ImagePath = @"/resources/Areas/Images/" + fileName;

                    using (var stream = new FileStream(destinationPath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }

                }
                else
                {
                    area.ImagePath = oldArea.ImagePath;
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _AreaService.UpdateAsync(area);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating area on database, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Area updated successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Delete(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _AreaService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int ID)
        {
            var Area = await _AreaService.FindByIDAsync(ID);
            if(Area == null)
            {
                return Content(@"notify('', 'Error: ID not found', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                if (System.IO.File.Exists(_appEnvironment.WebRootPath + "\\" + Area.ImagePath))
                {
                    System.IO.File.Delete(_appEnvironment.WebRootPath + "\\" + Area.ImagePath);
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error deleting image on server, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _AreaService.RemoveAsync(ID);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error deleting area on database, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Area deleted successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Details(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _AreaService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        public async Task<PartialViewResult> AddPartialEdit(string id)
        {
            int ID = int.Parse(id);
            Area area = await _AreaService.FindByIDAsync(ID);
            PartialViewResult partial = PartialView("Edit", area);
            return partial;
        }

        [HttpPost]
        public async Task<PartialViewResult> AddPartialDelete(string id)
        {
            int ID = int.Parse(id);
            Area area = await _AreaService.FindByIDAsync(ID);
            PartialViewResult partial = PartialView("Delete", area);
            return partial;
        }

    }
}

MachinePortal/Views/Areas/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model MachinePortal.Models.Area
@* Machine Photo Button and Preview *@
<script type="text/javascript">
    $(document).ready(function () {
        //Modal Close
        $("#closeModal01").on("click", function () {
            document.getElementById("divImageMediaPreview").innerHTML = "";
            document.getElementById("NameInput").value = "";
            document.getElementById("photo").value = "";
            document.getElementById("photoFilePath").value = "";
        });

        $("#closeModal02").on("click", function () {
            document.getElementById("divImageMediaPreview").innerHTML = "";
            document.getElementById("NameInput").value = "";
            document.getElementById("photo").value = "";
            document.getElementById("photoFilePath").value = "";
        });

        //Button triggers the photo file input
        document.getElementById('openPhoto').addEventListener('click', () => {
            document.getElementById('photo').click()
        });

        $("#photo").change(function () {
            //Get file name and put it into input
            var fileInput = document.getElementById('photo');
            for (i = 0; i < fileInput.files.length; i++) {
                var sfilename = fileInput.files[i].name;
                document.getElementById("photoFilePath").value = sfilename;
            }
            //Load file and show the preview
            if (typeof (FileReader) != "undefined") {
                var dvPreview = $("#divImageMediaPreview");
                dvPreview.html("");
                $($(this)[0].files).each(function () {
                    var file = $(this);
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = $("<img />");
                        img.attr("style", "height:200px; padding: 10px;");
                        img.attr("src", e.target.result);
                        img.attr("class", "img-thumbnail");
                        dvPreview.append(img);
                    }
                    reader.readAsDataURL(file[0]);
                });
            } else {
                notify('', 'Error: This browser does not support HTML5' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
            }
        });
    });
</script>

@* Send form through AJAX *@
<script type="text/javascript">
    $(document).ready(function () {
        $("form").submit(function (event) {
            event.preventDefault()
            $('.theme-loader').show();
            $.ajax({
                url: '@Url.Content("~/")' + "Areas/Create",
                type: "POST",
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                data: new FormData(this),
                success: function (m) {
                    $('.theme-loader').hide();
                    if (m == 'success') { window.location.href = "/Areas/Index"; };
                },
                error: function (e) {
                    $('.theme-loader').hide();
                    notify('', 'AJAX Request Error: ' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
                }
            });
        });
    });
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <form id="form" asp-controller="Areas" asp-action="Create" class="form" method="post" enctype="multipart/form-data">
            <div class="modal-header c-vitesco-green-03">
                <i style="color:white;font-size:30px;" class="bi-plus-circle c-vitesco-green-03"></i>
                <h3 style="color:white;text-align:center;" class="modal-title">@Localizer["Create Area"].Value</h3>
                <button style="color:white;margin-top:-8px;" type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="c-m-btn">×</span><span class="sr-only">@Localizer["Close"].Value</span></button>
            </div>
            <div class="modal-body">
                <div style="padding:10px;" class="form-horizontal">
                    <div class="form-group">
                        <div style="margin-bottom:10px;" id="divImageMediaPreview"></div>
                        <label class="control-label">Photo</label>
                        <div class="input-group">
                            <input id="photoFilePath" type="text" class="form-control" placeholder="@Localizer["No file chosen"].Value" readonly />
                            <span style="float:right;" class="input-group-append input-group-button">
                                <button id="openPhoto" class="btn btn-default" type="button">
                                    @Localizer["Open Photo"].Value
                                </button>
                            </span>
                        </div>
                        <input type="file" id="photo" name="image" accept="image/*" style="display:none" />
                    </div>
                    <label asp-for="Name" class="control-label"></label>
                    <input id="NameInput" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                    <br />
                </div>
            </div>
            <div class="modal-footer">
                <input id="closeModal02" style="width:120px;" type="button" value="@Localizer["Cancel"].Value" class="btn btn-primary mr-auto" data-dismiss="modal" />
                <input style="width:150px;float:right;" type="submit" value="@Localizer["Create"].Value" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

MachinePortal/Views/Areas/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model MachinePortal.Models.Area

@* Send form through AJAX *@
<script type="text/javascript">
    $(document).ready(function () {
        $("form").submit(function (event) {
            event.preventDefault()
            var ID = document.getElementById('ID').value;
            $.ajax({
                url: '@Url.Content("~/")' + "Areas/Delete",
                type: "POST",
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                data: { ID : ID },
                success: function (m) {
                    $('.theme-loader').hide();
                    if (m == 'success') { window.location.href = "/Areas/Index"; };
                },
                error: function (e) {
                    alert(e.responseText);
                }
            });
        });
    });
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <form id="form" asp-controller="Areas" asp-action="Delete" class="form" method="post">
            <div style="background-color: #dc3545;" class="modal-header">
                <i style="color:white;font-size:30px;background-color:#dc3545;" class="bi-x-circle"></i>
                <h3 style="color:white;text-align:center;" class="modal-title">@Localizer["Remove Area"].Value</h3>
                <button style="color:white;margin-top:-8px;" type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="c-m-btn">×</span><span class="sr-only">@Localizer["Close"].Value</span></button>
            </div>
            <div class="modal-body text-center">
                <div>
                    <dl class="dl-horizontal">
                        <dd>
                            <h4>@Html.DisplayFor(model => model.Name)</h4>
                            <hr />
                            @if (Model.ImagePath != null)
                            {
                                <td><img class="img-thumbnail" src="@Html.DisplayFor(model => model.ImagePath)" height="200" /></td>
                            }
                            else
                            {
                                <td><img class="img-thumbnail" src="~/resources/General/NoImage.jpg" width="200" /></td>
                            }
                        </dd>
                        <input id="ID" style="display:none" asp-for="ID" />
                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                <input style="width:150px;" type="button" value="@Localizer["Cancel"].Value" class="btn btn-primary mr-auto" data-dismiss="modal" />
                <input style="width:150px;float:right;" type="submit" value="@Localizer["Delete"].Value" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>