MachinePortal/Models/Line.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MachinePortal.Models
{
    public class Line
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        
        [Required]
        [StringLength(100, MinimumLength = 1)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        
        [Display(Name = "Photo")]
        public string ImagePath { get; set; }

        [Display(Name = "Sector ID")]
        public int SectorID { get; set; }
        [Display(Name = "Sector")]
        public Sector Sector { get; set; }

        public Line()
        {
        }

        public Line(int Id, string name, string imagePath)
        {
            ID = Id;
            Name = name;
            ImagePath = imagePath;
        }
    }
}

MachinePortal/Models/Machine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MachinePortal.Models
{
    public class Machine
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        
        [Required]
        [StringLength(100, MinimumLength = 3)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        
        [StringLength(200, MinimumLength = 3)]
        [Display(Name = "Description")]
        public string Description { get; set; }
        
        [Display(Name = "Photo")]
        public string ImagePath { get; set; }
        
        [Display(Name = "Asset Number")]
        public string AssetNumber { get; set; }
        
        [Display(Name = "MES Name")]
        public string MES_Name { get; set; }
        
        [Display(Name = "SAP Name")]
        public string SAP_Name { get; set; }

        [Display(Name = "Work Center")]
        public string WorkCenter { get; set; }
        
        [Display(Name = "Cost Center")]
        public string CostCenter { get; set; }
        
        [Display(Name = "Server Path")]
        public string ServerPath { get; set; }
        
        [Display(Name = "Last Preventive Maintenance Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime LastPreventiveMaintenance { get; set; }
        
        [Display(Name = "Manufactured Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime StartDate { get; set; }

        [Display(Name = "Area ID")]
        public int AreaID { get; set; }
        [Display(Name = "Area")]
        public Area Area { get; set; }

        [Display(Name = "Sector ID")]
        public int SectorID { get; set; }
        [Display(Name = "Sector")]
        public Sector Sector { get; set; }

        [Display(Name = "Line ID")]
        public int LineID { get; set; } 
        [Display(Name = "Line")]
        public Line Line { get; set; }

        [Display(Name = "Machine Documents")]
        public ICollection<MachineDocument> MachineDocuments { get; set; }
        [Display(Name = "Machine Comments")]
        public ICollection<MachineComment> MachineComments { get; set; }
        [Display(Name = "Machine Images")]
        public ICollection<MachineImage> MachineImages { get; set; }
        [Display(Name = "Machine Videos")]
        public ICollection<MachineVideo> MachineVideos { get; set; }
        [Display(Name = "Machine Responsibles")]
        public ICollection<MachineResponsible> MachineResponsibles { get; set; }
        [Display(Name = "Machine Devices")]
        public ICollection<MachineDevice> MachineDevices { get; set; }
        [Display(Name = "Passwords ")]
        public ICollection<Password> Passwords { get; set; }

        public void AddDocument(MachineDocument machineDocument)
        {
            MachineDocuments.Add(machineDocument);
        }

        public void AddImage(MachineImage machineImage)
        {
            MachineImages.Add(machineImage);
        }

        public void AddVideo(MachineVideo machineVideo)
        {
            MachineVideos.Add(machineVideo);
        }

    }
}

MachinePortal/Models/Sector.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MachinePortal.Models
{
    public class Sector
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        
        [Required]
        [StringLength(100, MinimumLength = 1)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        
        [Display(Name = "Photo")]
        public string ImagePath { get; set; }

        [Display(Name = "Lines")]
        public ICollection<Line> Lines { get; set; }

        [Display(Name = "Area ID")]
        public int AreaID { get; set; }
        [Display(Name = "Area")]
        public Area Area { get; set; }

        public Sector()
        {
        }

        public Sector(int Id, string name, string imagePath)
        {
            ID = Id;
            Name = name;
            ImagePath = imagePath;
        }
    }
}

MachinePortal/Controllers/HierarchiesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MachinePortal.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MachinePortal.Services;
using System.Security.Claims;
using MachinePortal.Areas.Identity.Data;

namespace MachinePortal.Controllers
{
    public class HierarchiesController : BaseController<HierarchiesController>
    {
        private readonly AreaService _AreaService;
        private readonly SectorService _SectorService;
        private readonly LineService _LineService;
        private readonly MachineService _MachineService;

        public HierarchiesController(AreaService areaService, SectorService sectorService, LineService lineService, MachineService machineService, PermissionsService permissionsService, IdentityContext identityContext)
        {
            _identityContext = identityContext;
            _AreaService = areaService;
            _SectorService = sectorService;
            _LineService = lineService;
            _MachineService = machineService;
            _PermissionsService = permissionsService;
        }

        public async Task<IActionResult> Index()
        {
            Permissions();
            var list = await _AreaService.FindAllAsync();
            return View(list);
        }

        public async Task<IActionResult> Sectors(int? ID)
        {
            Permissions();
            var list = await _SectorService.FindByAreaIDAsync(ID.Value);
            return View(list);
        }

        public async Task<IActionResult> Lines(int? ID)
        {
            Permissions();
            var list = await _LineService.FindBySectorIDAsync(ID.Value);
            return View(list);
        }

        public async Task<IActionResult> Machines(int? ID)
        {
            Permissions();
            var list = await _MachineService.FindByLine(ID.Value);
            return View(list);
        }
    }
}

MachinePortal/Controllers/LinesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MachinePortal.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MachinePortal.Services;
using MachinePortal.Models.ViewModels;
using System.Security.Claims;
using MachinePortal.Areas.Identity.Data;
using System.Web;

namespace MachinePortal.Controllers
{
    public class LinesController : BaseController<LinesController>
    {
        private readonly LineService _LineService;
        private readonly SectorService _SectorService;
        private readonly IHostingEnvironment _appEnvironment;

        public LinesController(IHostingEnvironment enviroment, LineService LineService, SectorService SectorService, PermissionsService permissionsService, IdentityContext identityContext)
        {
            _identityContext = identityContext;
            _SectorService = SectorService;
            _LineService = LineService;
            _PermissionsService = permissionsService;
            _appEnvironment = enviroment;
        }

        public async Task<IActionResult> Index()
        {
            Permissions();
            var list = await _LineService.FindAllAsync();
            return View(list);
        }

        public async Task<IActionResult> Create(int? sectorID)
        {
            Permissions();
            var viewModel = new LineFormViewModel
            {
                Line = new Line()
            };
            if (sectorID != null)
            {
                var sector = await _SectorService.FindByIDAsync(sectorID.Value);
                viewModel.Line.Sector = sector;
                viewModel.Line.SectorID = sector.ID;
            }   
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Line Line, IFormFile image)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new LineFormViewModel { Line = Line};
                return View(viewModel);
            }

            try
            {
                if (image != null)
                {
                    //long filesSize = image.Length;
                    //var filePath = Path.GetTempFileName();

                    if (image == null || image.Length == 0)
                    {
                        return Content(@"notify('', 'Error: file corrupted or not found', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
                    }

                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
                    fileName += image.FileName.Substring(image.FileName.LastIndexOf("."), (image.FileName.Length - image.FileName.LastIndexOf(".")));
                    string destinationPath = _appEnvironment.WebRootPath + "\\resources\\Lines\\Images\\" + fileName;
                    Line.ImagePath = @"/resources/Lines/Images/" + fileName;

                    using (var stream = new FileStream(destinationPath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error saving image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _LineService.InsertAsync(Line);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error adding line, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Line created successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Edit(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _LineService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Line Line, IFormFile image)
        {
            try
            {
                Line oldLine = await _LineService.FindByIDAsync(Line.ID);

                if (image != null)
                {
                    if (System.IO.File.Exists(_appEnvironment.WebRootPath + "\\" + Line.ImagePath))
                    {
                        System.IO.File.Delete(_appEnvironment.WebRootPath + "\\" + Line.ImagePath);
                    }

                    //long filesSize = image.Length;
                    //var filePath = Path.GetTempFileName();

                    if (image == null || image.Length == 0)
                    {
                        return Content(@"notify('', 'Error: No file selected', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
                    }

                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
                    fileName += image.FileName.Substring(image.FileName.LastIndexOf("."), (image.FileName.Length - image.FileName.LastIndexOf(".")));
                    string destinationPath = _appEnvironment.WebRootPath + "\\resources\\Lines\\Images\\" + fileName;
                    Line.ImagePath = @"/resources/Lines/Images/" + fileName;

                    using (var stream = new FileStream(destinationPath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }
                else
                {
                    Line.ImagePath = oldLine.ImagePath;
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _LineService.UpdateAsync(Line);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating line, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Line updated successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Delete(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _LineService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int ID)
        {
            var Line = await _LineService.FindByIDAsync(ID);
            if(Line == null)
            {
                return Content(@"notify('', 'ID not found', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                if (System.IO.File.Exists(_appEnvironment.WebRootPath + "\\" + Line.ImagePath))
                {
                    System.IO.File.Delete(_appEnvironment.WebRootPath + "\\" + Line.ImagePath);
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error removing image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _LineService.RemoveAsync(ID);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error removing line, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Line removed successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Details(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _LineService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        public async Task<PartialViewResult> AddPartialEdit(string id)
        {
            Line line;
            int ID = int.Parse(id);
            line = await _LineService.FindByIDAsync(ID);
            PartialViewResult partial = PartialView("Edit", line);
            return partial;
        }

        [HttpPost]

MachinePortal/Views/Hierarchies/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model IEnumerable<MachinePortal.Models.Area>

<div class="row justify-content-around">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
            <a asp-action="Sectors" asp-route-id="@item.ID">
                <div class="card fb-card c-vitesco-blue-03">
                    <div style="text-align:center" class="card-header c-vitesco-blue-03">
                        <div class="d-inline-block">
                            <h3 style="color:white;">@Html.DisplayFor(modelItem => item.Name)</h3>
                        </div>
                    </div>
                    <div style="text-align:center" class="card-block card-padding">
                        @if (item.ImagePath != null)
                        {
                            <img class="img-thumbnail" src="@Html.DisplayFor(modelItem => item.ImagePath)" width="350" />
                        }
                        else
                        {
                            <img class="img-thumbnail" src="~/resources/General/NoImage.jpg" width="350" />
                        }
                    </div>
                </div>
            </a>
        </div>
    }
</div>

MachinePortal/Views/Hierarchies/Lines.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model IEnumerable<MachinePortal.Models.Line>

<div class="row justify-content-around">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
            <a asp-controller="Hierarchies" asp-action="Machines" asp-route-id="@item.ID">
                <div class="card fb-card c-vitesco-blue-03">
                    <div style="text-align:center" class="card-header c-vitesco-blue-03">
                        <div class="d-inline-block">
                            <h3 style="color:white">@Html.DisplayFor(modelItem => item.Name)</h3>
                        </div>
                    </div>
                    <div style="text-align:center" class="card-block card-padding">
                        @if (item.ImagePath != null)
                        {
                            <img class="img-thumbnail" src="@Html.DisplayFor(modelItem => item.ImagePath)" width="250" />
                        }
                        else
                        {
                            <img class="img-thumbnail" src="~/resources/General/NoImage.jpg" width="250" />
                        }
                    </div>
                </div>
            </a>
        </div>
    }
</div>

MachinePortal/Views/Hierarchies/Machines.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model IEnumerable<MachinePortal.Models.Machine>

<div class="row justify-content-around">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
            <a asp-controller="Machines" asp-action="Details" asp-route-id="@item.ID">
                <div class="card fb-card c-vitesco-blue-03">
                    <div style="text-align:center" class="card-header c-vitesco-blue-03">
                        <div class="d-inline-block">
                            <h3 style="color:white">@Html.DisplayFor(modelItem => item.Name)</h3>
                        </div>
                    </div>
                    <div style="text-align:center" class="card-block card-padding">
                        @if (item.ImagePath != null)
                        {
                            <img class="img-thumbnail" src="@Html.DisplayFor(modelItem => item.ImagePath)" width="250" />
                        }
                        else
                        {
                            <img class="img-thumbnail" src="~/resources/General/NoImage.jpg" width="250" />
                        }
                    </div>
                </div>
            </a>
        </div>
    }
</div>

MachinePortal/Views/Hierarchies/Sectors.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model IEnumerable<MachinePortal.Models.Sector>

<div class="row justify-content-around">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
            <a asp-action="Lines" asp-route-id="@item.ID">
                <div class="card fb-card c-vitesco-blue-03">
                    <div style="text-align:center" class="card-header c-vitesco-blue-03">
                        <div class="d-inline-block">
                            <h3 style="color:white">@Html.DisplayFor(modelItem => item.Name)</h3>
                        </div>
                    </div>
                    <div style="text-align:center" class="card-block card-padding">
                        @if (item.ImagePath != null)
                        {
                            <img class="img-thumbnail" src="@Html.DisplayFor(modelItem => item.ImagePath)" width="250" />
                        }
                        else
                        {
                            <img class="img-thumbnail" src="~/resources/General/NoImage.jpg" width="250" />
                        }
                    </div>
                </div>
            </a>
        </div>
    }
</div>