MachinePortal/Models/Sector.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MachinePortal.Models
{
    public class Sector
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        
        [Required]
        [StringLength(100, MinimumLength = 1)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        
        [Display(Name = "Photo")]
        public string ImagePath { get; set; }

        [Display(Name = "Lines")]
        public ICollection<Line> Lines { get; set; }

        [Display(Name = "Area ID")]
        public int AreaID { get; set; }
        [Display(Name = "Area")]
        public Area Area { get; set; }

        public Sector()
        {
        }

        public Sector(int Id, string name, string imagePath)
        {
            ID = Id;
            Name = name;
            ImagePath = imagePath;
        }
    }
}

MachinePortal/Controllers/SectorsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MachinePortal.Models;
using MachinePortal.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MachinePortal.Services;
using System.Security.Claims;
using MachinePortal.Areas.Identity.Data;
using System.Web;

namespace MachinePortal.Controllers
{
    public class SectorsController : BaseController<SectorsController>
    {
        private readonly AreaService _AreaService;
        private readonly SectorService _SectorService;
        private readonly IHostingEnvironment _appEnvironment;

        public SectorsController(IHostingEnvironment enviroment, SectorService sectorService, AreaService areaService, PermissionsService permissionsService, IdentityContext identityContext)
        {
            _identityContext = identityContext;
            _PermissionsService = permissionsService;
            _AreaService = areaService;
            _SectorService = sectorService;
            _appEnvironment = enviroment;
        }

        public async Task<IActionResult> Index()
        {
            Permissions();
            var listSector = await _SectorService.FindAllAsync();
            return View(listSector);
        }

        public async Task<IActionResult> Create(int? areaID)
        {
            Permissions();
            var viewModel = new SectorFormViewModel
            {
                Sector = new Sector()
            };
            if (areaID != null)
            {
                var area = await _AreaService.FindByIDAsync(areaID.Value);
                viewModel.Sector.Area = area;
                viewModel.Sector.AreaID = area.ID;
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Sector Sector, IFormFile image)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new SectorFormViewModel { Sector = Sector };
                return View(viewModel);
            }

            try
            {
                Sector oldSector = await _SectorService.FindByIDAsync(Sector.ID);

                if (image != null)
                {
                    //long filesSize = image.Length;
                    //var filePath = Path.GetTempFileName();

                    if (image == null || image.Length == 0)
                    {
                        return Content(@"notify('', 'Error: No file selected', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
                    }

                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
                    fileName += image.FileName.Substring(image.FileName.LastIndexOf("."), (image.FileName.Length - image.FileName.LastIndexOf(".")));
                    string destinationPath = _appEnvironment.WebRootPath + "\\resources\\Sectors\\Images\\" + fileName;
                    Sector.ImagePath = @"/resources/Sectors/Images/" + fileName;

                    using (var stream = new FileStream(destinationPath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }
                else
                {
                    Sector.ImagePath = oldSector.ImagePath;
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error saving image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _SectorService.InsertAsync(Sector);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error adding sector, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Sector created successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Edit(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _SectorService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Sector Sector, IFormFile image)
        {
            try
            {
                if (image != null)
                {
                    if (System.IO.File.Exists(_appEnvironment.WebRootPath + "\\" + Sector.ImagePath))
                    {
                        System.IO.File.Delete(_appEnvironment.WebRootPath + "\\" + Sector.ImagePath);
                    }

                    //long filesSize = image.Length;
                    //var filePath = Path.GetTempFileName();

                    if (image == null || image.Length == 0)
                    {
                        return Content(@"notify('', 'Error: No file selected', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
                    }

                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
                    fileName += image.FileName.Substring(image.FileName.LastIndexOf("."), (image.FileName.Length - image.FileName.LastIndexOf(".")));
                    string destinationPath = _appEnvironment.WebRootPath + "\\resources\\Sectors\\Images\\" + fileName;
                    Sector.ImagePath = @"/resources/Sectors/Images/" + fileName;

                    using (var stream = new FileStream(destinationPath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }
            
            try
            {
                await _SectorService.UpdateAsync(Sector);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating sector, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Sector updated successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Delete(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _SectorService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int ID)
        {
            var Sector = await _SectorService.FindByIDAsync(ID);
            if (Sector == null)
            {
                return Content(@"notify('', 'ID not found', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                if (System.IO.File.Exists(_appEnvironment.WebRootPath + "\\" + Sector.ImagePath))
                {
                    System.IO.File.Delete(_appEnvironment.WebRootPath + "\\" + Sector.ImagePath);
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error removing image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _SectorService.RemoveAsync(ID);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error removing sector, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Sector removed successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Details(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _SectorService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //Partials 
        [HttpPost]
        public async Task<PartialViewResult> AddPartialEdit(string id)
        {
            Sector sector;
            int ID = int.Parse(id);
            sector = await _SectorService.FindByIDAsync(ID);

MachinePortal/Views/Sectors/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model MachinePortal.Models.ViewModels.SectorFormViewModel
@* Machine Photo Button and Preview *@
<script type="text/javascript">
    $(document).ready(function () {
        //Modal Close
        $("#closeModal01").on("click", function () {
            document.getElementById("divImageMediaPreview").innerHTML = "";
            document.getElementById("NameInput").value = "";
            document.getElementById("photo").value = "";
            document.getElementById("photoFilePath").value = "";
        });

        $("#closeModal02").on("click", function () {
            document.getElementById("divImageMediaPreview").innerHTML = "";
            document.getElementById("NameInput").value = "";
            document.getElementById("photo").value = "";
            document.getElementById("photoFilePath").value = "";
        });

        //Button triggers the photo file input
        document.getElementById('openPhoto').addEventListener('click', () => {
            document.getElementById('photo').click()
        });

        $("#photo").change(function () {
            //Get file name and put it into input
            var fileInput = document.getElementById('photo');
            for (i = 0; i < fileInput.files.length; i++) {
                var sfilename = fileInput.files[i].name;
                document.getElementById("photoFilePath").value = sfilename;
            }
            //Load file and show the preview
            if (typeof (FileReader) != "undefined") {
                var dvPreview = $("#divImageMediaPreview");
                dvPreview.html("");
                $($(this)[0].files).each(function () {
                    var file = $(this);
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = $("<img />");
                        img.attr("style", "height:200px; padding: 10px;");
                        img.attr("src", e.target.result);
                        img.attr("class", "img-thumbnail");
                        dvPreview.append(img);
                    }
                    reader.readAsDataURL(file[0]);
                });
            } else {
                notify('', 'Error: This browser does not support HTML5' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
            }
        });
    });
</script>

@* Send form through AJAX *@
<script type="text/javascript">
    $(document).ready(function () {
        $("form").submit(function (event) {
            event.preventDefault()
            $('.theme-loader').show();
            $.ajax({
                url: '@Url.Content("~/")' + "Sectors/Create",
                type: "POST",
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                processData: false,
                contentType: false,
                data: new FormData(this),
                success: function (m) {
                    $('.theme-loader').hide();
                    if (m == 'success') { window.location.href = "/Areas/Details/" + @Model.Sector.AreaID; };
                },
                error: function (e) {
                    $('.theme-loader').hide();
                    notify('', 'AJAX Request Error: ' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
                }
            });
        });
    });
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <form id="form" asp-controller="Sectors" asp-action="Create" class="form" method="post" enctype="multipart/form-data">
            <div class="modal-header c-vitesco-green-03">
                <i style="color:white;font-size:30px;" class="bi-plus-circle c-vitesco-green-03"></i>
                <h3 style="color:white;text-align:center;" class="modal-title">@Localizer["Create New Sector"].Value</h3>
                <button style="color:white;margin-top:-8px;" type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="c-m-btn">×</span><span class="sr-only">@Localizer["Close"].Value</span></button>
            </div>
            <div class="modal-body">
                <div style="padding:10px;" class="form-horizontal">
                    <div class="form-group">
                        <div style="margin-bottom:10px;" id="divImageMediaPreview"></div>
                        <label class="control-label">@Localizer["Photo"].Value</label>
                        <div class="input-group">
                            <input id="photoFilePath" type="text" class="form-control" placeholder="@Localizer["No file chosen"].Value" readonly />
                            <span style="float:right;" class="input-group-append input-group-button">
                                <button id="openPhoto" class="btn btn-default" type="button">
                                    @Localizer["Open Photo"].Value
                                </button>
                            </span>
                        </div>
                        <input type="file" id="photo" name="image" accept="image/*" style="display:none" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Sector.Name" class="control-label"></label>
                        <input asp-for="Sector.Name" class="form-control" />
                        <span asp-validation-for="Sector.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="hidden" asp-for="Sector.AreaID" class="form-control"></input>
                    </div>
                    <br />
                </div>
            </div>
            <div class="modal-footer">
                <input id="closeModal02" style="width:120px;" type="button" value="@Localizer["Cancel"].Value" class="btn btn-primary mr-auto" data-dismiss="modal" />
                <input style="width:150px;float:right;" type="submit" value="@Localizer["Create"].Value" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

MachinePortal/Views/Sectors/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model MachinePortal.Models.Sector

@* Send form through AJAX *@
<script type="text/javascript">
    $(document).ready(function () {
        $("form").submit(function (event) {
            event.preventDefault()
            var ID = document.getElementById('ID').value;
            $.ajax({
                url: '@Url.Content("~/")' + "Sectors/Delete",
                type: "POST",
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                data: { ID : ID },
                success: function (m) {
                    $('.theme-loader').hide();
                    if (m == 'success') { window.location.href = "/Areas/Details/" + @Model.AreaID; };
                },
                error: function (e) {
                    alert(e.responseText);
                }
            });
        });
    });
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <form id="form" asp-controller="Sectors" asp-action="Delete" class="form" method="post">
            <div style="background-color: #dc3545;" class="modal-header">
                <i style="color:white;font-size:30px;background-color:#dc3545;" class="bi-x-circle"></i>
                <h3 style="color:white;text-align:center;" class="modal-title">@Localizer["Remove Sector"].Value</h3>
                <button style="color:white;margin-top:-8px;" type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="c-m-btn">×</span><span class="sr-only">@Localizer["Close"].Value</span></button>
            </div>
            <div class="modal-body text-center">
                <div>
                    <dl class="dl-horizontal">
                        <dd>
                            <h4>@Html.DisplayFor(model => model.Name)</h4>
                            <hr />
                            @if (Model.ImagePath != null)
                            {
                                <td><img class="img-thumbnail" src="@Html.DisplayFor(model => model.ImagePath)" height="200" /></td>
                            }
                            else
                            {
                                <td><img class="img-thumbnail" src="~/resources/General/NoImage.jpg" width="200" /></td>
                            }
                        </dd>
                        <input style="display:none" asp-for="ID" />
                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" asp-for="ID" />
                <input style="width:150px;" type="button" value="@Localizer["Cancel"].Value" class="btn btn-primary mr-auto" data-dismiss="modal" />
                <input style="width:150px;float:right;" type="submit" value="@Localizer["Delete"].Value" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

MachinePortal/Views/Sectors/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model MachinePortal.Models.Sector

<script>
    $(document).ajaxComplete(function (event, xhr, settings) {
        //Button triggers the photo file input
        document.getElementById('openPhotoEdit').addEventListener('click', () => {
            document.getElementById('photoEdit').click()
        });

        $("#photoEdit").change(function () {
            //Get file name and put it into input
            var fileInput = document.getElementById('photoEdit');
            for (i = 0; i < fileInput.files.length; i++) {
                var sfilename = fileInput.files[i].name;
                document.getElementById("photoFilePathEdit").value = sfilename;
            }
            //Load file and show the preview
            if (typeof (FileReader) != "undefined") {
                var dvPreview = $("#divImageMediaPreviewEdit");
                dvPreview.html("");
                var formData = new FormData();
                var filesLength = document.getElementById('photoEdit').files.length;
                for (var i = 0; i < filesLength; i++) {
                    var file = document.getElementById('photoEdit').files[i];
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = $("<img />");
                        img.attr("style", "height:200px; margin: 10px;");
                        img.attr("src", e.target.result);
                        img.attr("class", "img-thumbnail");
                        dvPreview.append(img);
                    }
                    reader.readAsDataURL(file);
                }
            } else {
                notify('', 'Error: This browser does not support HTML5' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
            }
        });
    });
</script>

@* Send form through AJAX *@
<script type="text/javascript">
    $(document).ready(function () {
        $("form").submit(function (event) {
            event.preventDefault()
            $('.theme-loader').show();
            $.ajax({
                url: '@Url.Content("~/")' + "Sectors/Edit",
                type: "POST",
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                processData: false,
                contentType: false,
                data: new FormData(this),
                success: function (m) {
                    $('.theme-loader').hide();
                    if (m == 'success') { window.location.href = "/Areas/Details/" + @Model.AreaID; };
                },
                error: function (e) {
                    $('.theme-loader').hide();
                    notify('', 'AJAX Request Error: ' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
                }
            });
        });
    });
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <form id="form" asp-controller="Sectors" asp-action="Edit" class="form" method="post" enctype="multipart/form-data">
            <div class="modal-header c-vitesco-blue-03">
                <i style="color:white;font-size:30px;" class="bi-pencil c-vitesco-blue-03"></i>
                <h3 style="color:white;text-align:center;" class="modal-title">@Localizer["Edit:"].Value @Model.Name</h3>
                <button style="color:white;margin-top:-8px;" type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="c-m-btn">×</span><span class="sr-only">@Localizer["Close"].Value</span></button>
            </div>
            <div class="modal-body">
                <div style="padding:10px;" class="form-horizontal">
                    <div class="form-group">
                        <div id="divImageMediaPreviewEdit"></div>
                        <label class="control-label">@Localizer["Photo"].Value</label>
                        <div class="input-group">
                            <input id="photoFilePathEdit" type="text" class="form-control" placeholder="@Localizer["No file chosen"].Value" readonly />
                            <span class="input-group-append input-group-button">
                                <button id="openPhotoEdit" class="btn btn-default" type="button">
                                    @Localizer["Open Photo"].Value
                                </button>
                            </span>
                        </div>
                        <input type="file" id="photoEdit" name="image" accept="image/*" style="display:none" />
                    </div>
                    @* Save Sector ID *@
                    <div class="form-group">
                        <input asp-for="ID" style="display:none" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Lines" class="control-label"></label>
                        <select asp-for="Lines" asp-items="@(new SelectList(Model.Lines,"ID","Name"))" class="form-control" multiple></select>
                    </div>
                    <input style="display:none" asp-for="AreaID" />
                </div>
            </div>
            <div class="modal-footer">
                <input id="closeModal02" style="width:120px;" type="button" value="@Localizer["Cancel"].Value" class="btn btn-primary mr-auto" data-dismiss="modal" />
                <input style="width:150px;float:right;" type="submit" value="@Localizer["Edit"].Value" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>