MachinePortal/Models/Line.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MachinePortal.Models
{
    public class Line
    {
        [Display(Name = "ID")]
        public int ID { get; set; }
        
        [Required]
        [StringLength(100, MinimumLength = 1)]
        [Display(Name = "Name")]
        public string Name { get; set; }
        
        [Display(Name = "Photo")]
        public string ImagePath { get; set; }

        [Display(Name = "Sector ID")]
        public int SectorID { get; set; }
        [Display(Name = "Sector")]
        public Sector Sector { get; set; }

        public Line()
        {
        }

        public Line(int Id, string name, string imagePath)
        {
            ID = Id;
            Name = name;
            ImagePath = imagePath;
        }
    }
}

MachinePortal/Controllers/LinesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MachinePortal.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MachinePortal.Services;
using MachinePortal.Models.ViewModels;
using System.Security.Claims;
using MachinePortal.Areas.Identity.Data;
using System.Web;

namespace MachinePortal.Controllers
{
    public class LinesController : BaseController<LinesController>
    {
        private readonly LineService _LineService;
        private readonly SectorService _SectorService;
        private readonly IHostingEnvironment _appEnvironment;

        public LinesController(IHostingEnvironment enviroment, LineService LineService, SectorService SectorService, PermissionsService permissionsService, IdentityContext identityContext)
        {
            _identityContext = identityContext;
            _SectorService = SectorService;
            _LineService = LineService;
            _PermissionsService = permissionsService;
            _appEnvironment = enviroment;
        }

        public async Task<IActionResult> Index()
        {
            Permissions();
            var list = await _LineService.FindAllAsync();
            return View(list);
        }

        public async Task<IActionResult> Create(int? sectorID)
        {
            Permissions();
            var viewModel = new LineFormViewModel
            {
                Line = new Line()
            };
            if (sectorID != null)
            {
                var sector = await _SectorService.FindByIDAsync(sectorID.Value);
                viewModel.Line.Sector = sector;
                viewModel.Line.SectorID = sector.ID;
            }   
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Line Line, IFormFile image)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new LineFormViewModel { Line = Line};
                return View(viewModel);
            }

            try
            {
                if (image != null)
                {
                    //long filesSize = image.Length;
                    //var filePath = Path.GetTempFileName();

                    if (image == null || image.Length == 0)
                    {
                        return Content(@"notify('', 'Error: file corrupted or not found', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
                    }

                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
                    fileName += image.FileName.Substring(image.FileName.LastIndexOf("."), (image.FileName.Length - image.FileName.LastIndexOf(".")));
                    string destinationPath = _appEnvironment.WebRootPath + "\\resources\\Lines\\Images\\" + fileName;
                    Line.ImagePath = @"/resources/Lines/Images/" + fileName;

                    using (var stream = new FileStream(destinationPath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error saving image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _LineService.InsertAsync(Line);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error adding line, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Line created successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Edit(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _LineService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Line Line, IFormFile image)
        {
            try
            {
                Line oldLine = await _LineService.FindByIDAsync(Line.ID);

                if (image != null)
                {
                    if (System.IO.File.Exists(_appEnvironment.WebRootPath + "\\" + Line.ImagePath))
                    {
                        System.IO.File.Delete(_appEnvironment.WebRootPath + "\\" + Line.ImagePath);
                    }

                    //long filesSize = image.Length;
                    //var filePath = Path.GetTempFileName();

                    if (image == null || image.Length == 0)
                    {
                        return Content(@"notify('', 'Error: No file selected', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
                    }

                    string fileName = DateTime.Now.ToString("yyyyMMddHHmmss");
                    fileName += image.FileName.Substring(image.FileName.LastIndexOf("."), (image.FileName.Length - image.FileName.LastIndexOf(".")));
                    string destinationPath = _appEnvironment.WebRootPath + "\\resources\\Lines\\Images\\" + fileName;
                    Line.ImagePath = @"/resources/Lines/Images/" + fileName;

                    using (var stream = new FileStream(destinationPath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                }
                else
                {
                    Line.ImagePath = oldLine.ImagePath;
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _LineService.UpdateAsync(Line);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error updating line, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Line updated successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Delete(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _LineService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int ID)
        {
            var Line = await _LineService.FindByIDAsync(ID);
            if(Line == null)
            {
                return Content(@"notify('', 'ID not found', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                if (System.IO.File.Exists(_appEnvironment.WebRootPath + "\\" + Line.ImagePath))
                {
                    System.IO.File.Delete(_appEnvironment.WebRootPath + "\\" + Line.ImagePath);
                }
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error removing image, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            try
            {
                await _LineService.RemoveAsync(ID);
            }
            catch (Exception e)
            {
                return Content(@"notify('', '" + "Error removing line, description: " + HttpUtility.JavaScriptStringEncode(e.Message) + @"', 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight')", "application/javascript");
            }

            TempData["notificationMessage"] = "Line removed successfuly";
            TempData["notificationIcon"] = "bi-check-circle";
            TempData["notificationType"] = "success";
            return Content("success");
        }

        public async Task<IActionResult> Details(int? ID)
        {
            Permissions();
            if (ID == null)
            {
                return NotFound();
            }
            var obj = await _LineService.FindByIDAsync(ID.Value);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        public async Task<PartialViewResult> AddPartialEdit(string id)
        {
            Line line;
            int ID = int.Parse(id);
            line = await _LineService.FindByIDAsync(ID);
            PartialViewResult partial = PartialView("Edit", line);
            return partial;
        }

        [HttpPost]

MachinePortal/Views/Lines/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model MachinePortal.Models.ViewModels.LineFormViewModel

@* Machine Photo Button and Preview *@
<script type="text/javascript">
    $(document).ready(function () {
        //Modal Close
        $("#closeModal01").on("click", function () {
            document.getElementById("divImageMediaPreview").innerHTML = "";
            document.getElementById("NameInput").value = "";
            document.getElementById("photo").value = "";
            document.getElementById("photoFilePath").value = "";
        });

        $("#closeModal02").on("click", function () {
            document.getElementById("divImageMediaPreview").innerHTML = "";
            document.getElementById("NameInput").value = "";
            document.getElementById("photo").value = "";
            document.getElementById("photoFilePath").value = "";
        });

        //Button triggers the photo file input
        document.getElementById('openPhoto').addEventListener('click', () => {
            document.getElementById('photo').click()
        });

        $("#photo").change(function () {
            //Get file name and put it into input
            var fileInput = document.getElementById('photo');
            for (i = 0; i < fileInput.files.length; i++) {
                var sfilename = fileInput.files[i].name;
                document.getElementById("photoFilePath").value = sfilename;
            }
            //Load file and show the preview
            if (typeof (FileReader) != "undefined") {
                var dvPreview = $("#divImageMediaPreview");
                dvPreview.html("");
                $($(this)[0].files).each(function () {
                    var file = $(this);
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = $("<img />");
                        img.attr("style", "height:200px; padding: 10px;");
                        img.attr("src", e.target.result);
                        img.attr("class", "img-thumbnail");
                        dvPreview.append(img);
                    }
                    reader.readAsDataURL(file[0]);
                });
            } else {
                notify('', 'Error: This browser does not support HTML5' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
            }
        });
    });
</script>

@* Send form through AJAX *@
<script type="text/javascript">
    $(document).ready(function () {
        $("form").submit(function (event) {
            event.preventDefault()
            $('.theme-loader').show();
            $.ajax({
                url: '@Url.Content("~/")' + "Lines/Create",
                type: "POST",
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                processData: false,
                contentType: false,
                data: new FormData(this),
                success: function (m) {
                    $('.theme-loader').hide();
                    if (m == 'success') { window.location.href = "/Sectors/Details/" + @Model.Line.SectorID; };
                },
                error: function (e) {
                    $('.theme-loader').hide();
                    notify('', 'AJAX Request Error: ' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
                }
            });
        });
    });
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <form id="form" asp-controller="Lines" asp-action="Create" class="form" method="post" enctype="multipart/form-data">
            <div class="modal-header c-vitesco-green-03">
                <i style="color:white;font-size:30px;" class="bi-plus-circle c-vitesco-green-03"></i>
                <h3 style="color:white;text-align:center;" class="modal-title">@Localizer["Create New Line"].Value</h3>
                <button style="color:white;margin-top:-8px;" type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="c-m-btn">×</span><span class="sr-only">@Localizer["Close"].Value</span></button>
            </div>
            <div class="modal-body">
                <div style="padding:10px;" class="form-horizontal">
                    <div class="form-group">
                        <div style="margin-bottom:10px;" id="divImageMediaPreview"></div>
                        <label class="control-label">Photo</label>
                        <div class="input-group">
                            <input id="photoFilePath" type="text" class="form-control" placeholder="@Localizer["No file chosen"].Value" readonly />
                            <span style="float:right;" class="input-group-append input-group-button">
                                <button id="openPhoto" class="btn btn-default" type="button">
                                    @Localizer["Open Photo"].Value
                                </button>
                            </span>
                        </div>
                        <input type="file" id="photo" name="image" accept="image/*" style="display:none" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Line.Name" class="control-label"></label>
                        <input asp-for="Line.Name" class="form-control" />
                        <span asp-validation-for="Line.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="hidden" asp-for="Line.SectorID" class="form-control"></input>
                    </div>
                    <br />
                </div>
            </div>
            <div class="modal-footer">
                <input id="closeModal02" style="width:120px;" type="button" value="@Localizer["Cancel"].Value" class="btn btn-primary mr-auto" data-dismiss="modal" />
                <input style="width:150px;float:right;" type="submit" value="@Localizer["Create"].Value" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

MachinePortal/Views/Lines/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model MachinePortal.Models.Line

@* Send form through AJAX *@
<script type="text/javascript">
    $(document).ready(function () {
        $("form").submit(function (event) {
            event.preventDefault()
            var ID = document.getElementById('ID').value;
            $.ajax({
                url: '@Url.Content("~/")' + "Lines/Delete",
                type: "POST",
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                data: { ID : ID },
                success: function (m) {
                    $('.theme-loader').hide();
                    if (m == 'success') { window.location.href = "/Sectors/Details/" + @Model.SectorID; };
                },
                error: function (e) {
                    alert(e.responseText);
                }
            });
        });
    });
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <form id="form" asp-controller="Lines" asp-action="Delete" class="form" method="post">
            <div style="background-color: #dc3545;" class="modal-header">
                <i style="color:white;font-size:30px;background-color:#dc3545;" class="bi-x-circle"></i>
                <h3 style="color:white;text-align:center;" class="modal-title">@Localizer["Remove Line"].Value</h3>
                <button style="color:white;margin-top:-8px;" type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="c-m-btn">×</span><span class="sr-only">@Localizer["Close"].Value</span></button>
            </div>
            <div class="modal-body text-center">
                <div>
                    <dl class="dl-horizontal">
                        <dd>
                            <h4>@Html.DisplayFor(model => model.Name)</h4>
                            <hr />
                            @if (Model.ImagePath != null)
                            {
                                <td><img class="img-thumbnail" src="@Html.DisplayFor(model => model.ImagePath)" height="200" /></td>
                            }
                            else
                            {
                                <td><img class="img-thumbnail" src="~/resources/General/NoImage.jpg" width="200" /></td>
                            }
                        </dd>
                        <input style="display:none" asp-for="ID" />
                    </dl>
                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" asp-for="ID" />
                <input style="width:150px;" type="button" value="@Localizer["Cancel"].Value" class="btn btn-primary mr-auto" data-dismiss="modal" />
                <input style="width:150px;float:right;" type="submit" value="@Localizer["Delete"].Value" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

MachinePortal/Views/Lines/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model MachinePortal.Models.Line

<script>
    $(document).ajaxComplete(function (event, xhr, settings) {
        //Button triggers the photo file input
        document.getElementById('openPhotoEdit').addEventListener('click', () => {
            document.getElementById('photoEdit').click()
        });

        $("#photoEdit").change(function () {
            //Get file name and put it into input
            var fileInput = document.getElementById('photoEdit');
            for (i = 0; i < fileInput.files.length; i++) {
                var sfilename = fileInput.files[i].name;
                document.getElementById("photoFilePathEdit").value = sfilename;
            }
            //Load file and show the preview
            if (typeof (FileReader) != "undefined") {
                var dvPreview = $("#divImageMediaPreviewEdit");
                dvPreview.html("");
                var formData = new FormData();
                var filesLength = document.getElementById('photoEdit').files.length;
                for (var i = 0; i < filesLength; i++) {
                    var file = document.getElementById('photoEdit').files[i];
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = $("<img />");
                        img.attr("style", "height:200px; margin: 10px;");
                        img.attr("src", e.target.result);
                        img.attr("class", "img-thumbnail");
                        dvPreview.append(img);
                    }
                    reader.readAsDataURL(file);
                }
            } else {
                notify('', 'Error: This browser does not support HTML5' + e.statusText, 'top', 'right', 'bi-x-circle', 'error', 'fadeInRight', 'fadeInRight');
            }
        });
    });
</script>

@* Send form through AJAX *@
<script type="text/javascript">
    $(document).ready(function () {
        $("form").submit(function (event) {
            event.preventDefault()
            $.ajax({
                url: '@Url.Content("~/")' + "Lines/Edit",
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                type: "POST",
                data: new FormData(this),
                processData: false,
                contentType: false,
                success: function (m) {
                    $('.theme-loader').hide();
                    if (m == 'success') { window.location.href = "/Sectors/Details/" + @Model.SectorID; };
                },
                error: function (e) {
                    alert(e.responseText);
                }
            });
        });
    });
</script>

<div class="modal-dialog">
    <div class="modal-content">
        <form id="form" asp-controller="Lines" asp-action="Edit" class="form" method="post" enctype="multipart/form-data">
            <div class="modal-header c-vitesco-blue-03">
                <i style="color:white;font-size:30px;" class="bi-pencil c-vitesco-blue-03"></i>
                <h3 style="color:white;text-align:center;" class="modal-title">@Localizer["Edit"].Value: @Model.Name</h3>
                <button style="color:white;margin-top:-8px;" type="button" class="close" data-dismiss="modal"><span aria-hidden="true" class="c-m-btn">×</span><span class="sr-only">@Localizer["Close"].Value</span></button>
            </div>
            <div class="modal-body">
                <div style="padding:10px;" class="form-horizontal">
                    <div class="form-group">
                        <div id="divImageMediaPreviewEdit"></div>
                        <label class="control-label">@Localizer["Photo"].Value</label>
                        <div class="input-group">
                            <input id="photoFilePathEdit" type="text" class="form-control" placeholder="@Localizer["No file chosen"].Value" readonly />
                            <span class="input-group-append input-group-button">
                                <button id="openPhotoEdit" class="btn btn-default" type="button">
                                    @Localizer["Open Photo"].Value
                                </button>
                            </span>
                        </div>
                        <input type="file" id="photoEdit" name="image" accept="image/*" style="display:none" />
                    </div>
                    @* Save Line ID *@
                    <div class="form-group">
                        <input asp-for="ID" style="display:none" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <input style="display:none" asp-for="SectorID" />
                </div>
            </div>
            <div class="modal-footer">
                <input id="closeModal02" style="width:120px;" type="button" value="@Localizer["Cancel"].Value" class="btn btn-primary mr-auto" data-dismiss="modal" />
                <input style="width:150px;float:right;" type="submit" value="@Localizer["Edit"].Value" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

MachinePortal/Views/Lines/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model IEnumerable<MachinePortal.Models.Line>
@* Check User Permissions *@
@using Microsoft.AspNetCore.Identity
@using MachinePortal.Areas.Identity.Data
@using Microsoft.EntityFrameworkCore
@inject UserManager<MachinePortalUser> UserManager
@inject IdentityContext identityContext
@{
    var user = await UserManager.GetUserAsync(User);
    List<string> permissions = new List<string>();
    if (user != null) { permissions = ((from obj in identityContext.UserPermission select obj).Include(p => p.Permission).Where(x => x.UserID == user.Id).ToList()).Select(p => p.Permission.PermissionName).ToList(); };
    if (!permissions.Contains("PageHierarchies")) { Context.Response.Redirect("/Home/AccessDenied"); };
}

@{
    string notMessage = (TempData["notificationMessage"] != null) ? TempData["notificationMessage"].ToString() : "";
    string notIcon = (TempData["notificationIcon"] != null) ? TempData["notificationIcon"].ToString() : "";
    string notType = (TempData["notificationType"] != null) ? TempData["notificationType"].ToString() : "";
}

<script>
    $(document).ready(function () {
        if ('@notMessage' != '') {
            notify('', '@notMessage', 'top', 'right', '@notIcon', '@notType', 'fadeInRight', 'fadeInRight');
        };
    });
</script>

<script>
    function renderPartialEdit(ID) {
        $.ajax({
            url: '@Url.Action("AddPartialEdit", "Lines")',
            data: { id: ID},
            type: "POST",
            success: function(data) {
                $('#modalEdit').html(data);
            }
        });
    }

    function renderPartialDelete(ID) {
        $.ajax({
            url: '@Url.Action("AddPartialDelete", "Lines")',
            data: { id: ID},
            type: "POST",
            success: function(data) {
                $('#modalDelete').html(data);
            }
        });
    }
</script>

<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-10">
        <div class="card fb-card c-vitesco-green-05">
            <div class="card-header c-vitesco-green-05">
                <i style="vertical-align:middle" class="ti-layout-list-thumb c-vitesco-green-05"></i>
                <div class="d-inline-block">
                    <h2 style="color:white;">@Localizer["Hierarchies"].Value</h2>
                </div>
                <hr style="border:1px solid white" />
                <div class="d-inline-block">
                    <h2 style="color:white">@Localizer["Lines"].Value</h2>
                </div>
            </div>
            <div class="card-block card-padding">
                <div class="table-responsive">
                    <div class="table-responsive">
                        <table style="table-layout:auto;" class="table table-hover table-bordered table-vitesco">
                            <thead class="thead-vitesco">
                                <tr>
                                    <th width="15%">@Html.DisplayNameFor(model => model.ImagePath)</th>
                                    <th width="65%">@Html.DisplayNameFor(model => model.Name)</th>
                                    <th width="20%" class="text-center">Options</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        @if (item.ImagePath != null)
                                        {
                                            <td class="text-center"><img src="@Html.DisplayFor(modelItem => item.ImagePath)" width="100" /></td>
                                        }
                                        else
                                        {
                                            <td class="text-center"><img src="~/resources/General/NoImage.jpg" width="100" /></td>
                                        }
                                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                        <td class="text-center ws-nowrap">
                                            <a class="btn btn-success" asp-action="Details" asp-route-id="@item.ID">@Localizer["Open"].Value</a>
                                            @if (permissions.Contains("HierarchiesEdit"))
                                            {
                                                <button class="btn btn-primary" data-toggle="modal" onclick="renderPartialEdit(@item.ID)" data-target="#modalEdit">@Localizer["Edit"].Value</button>
                                            }
                                            @if (permissions.Contains("HierarchiesDelete"))
                                            {
                                                <button class="btn btn-danger" data-toggle="modal" onclick="renderPartialDelete(@item.ID)" data-target="#modalDelete">@Localizer["Delete"].Value</button>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <br />
                <a style="width:150px;" class="btn btn-primary" asp-controller="Lines" asp-action="Index">@Localizer["Back"].Value</a>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="modalEdit" role="dialog">
</div>
<div class="modal" id="modalDelete" role="dialog">
</div>